### PR TITLE
Add style for inline paragraph code

### PR DESCRIPTION
**Pull request by federicobucchi**
### Motivation:

I noticed that inline code inside paragraphs is not highlighted as I think it should.  I think it would be nice to style a bit the inline code to have it more "noticeable" in paragraphs

### Modifications:

Added style in:
- assets/stylesheets/_screen.scss

### Result:

From

Screenshot 2024-03-01 at 12 42 36 PM

To

Screenshot 2024-03-01 at 12 48 01 PM

From

Screenshot 2024-03-01 at 12 49 09 PM

To

Screenshot 2024-03-01 at 12 48 52 PM

From

Screenshot 2024-03-01 at 12 47 18 PM

To

Screenshot 2024-03-01 at 12 46 55 PM

From

Screenshot 2024-03-01 at 12 49 53 PM

To

Screenshot 2024-03-01 at 12 50 32 PM

### CODE REVIEW

**Comment by federicobucchi** [comment]
@swift-ci please test

**Comment by dempseyatgithub** [comment]
I believe this is a good change overall.

I think the dark mode highlight could be a bit lighter. At actual size, I was looking at the dark mode before/after screen captures and couldn't see any difference between the two. I had to zoom in before I could see the highlight.

The light mode highlight is more obvious as-is.

**Comment by federicobucchi** [comment]
@dempseyatgithub I made the style more clear for both `light` and `dark` mode

Screenshot 2024-03-03 at 10 20 28 AM

Screenshot 2024-03-03 at 10 20 34 AM

**Comment by federicobucchi** [comment]
@swift-ci please test

**Comment by dempseyatgithub** [comment]
I think with the second iteration that the border around the text is way too prominent.

I was hoping with my original feedback to see a slightly lighter background color in dark mode, and possibly a slightly darker background color in light mode

I think the original color of the border in the original was okay.

**Comment by federicobucchi** [comment]
@swift-ci please test

**Comment by federicobucchi** [comment]
@dempseyatgithub 

Screenshot 2024-03-14 at 4 54 53 PM

Screenshot 2024-03-14 at 4 55 03 PM

**Review by alexandersandberg — COMMENTED** [review]
I think I like the first version with the subtle border best, to match the bigger code blocks, but happy with just the background too.

**Comment by federicobucchi** [comment]
@dempseyatgithub @alexandersandberg thanks!  All these versions, for me, are an improvement.  Just let me know which one both of you agree on and we can get this in!

**Comment by dempseyatgithub** [comment]
@federicobucchi 
Of the three options, I also prefer the first one. So, I guess let's go with that.

**Comment by federicobucchi** [comment]
@dempseyatgithub ok 👍🏻 

@dempseyatgithub @alexandersandberg I have applied the first style:

Screenshot 2024-03-17 at 2 45 23 PM

---

Screenshot 2024-03-17 at 2 45 34 PM

**Comment by federicobucchi** [comment]
@swift-ci please test

**Comment by dempseyatgithub** [comment]
@swift-ci test

**Review by dempseyatgithub — APPROVED** [review]
Looking forward to seeing this on the site!

**Review by alexandersandberg — APPROVED** [review]
✨

**Pull request merged**
