### PR TITLE
[GSoC] Add section with tips of how to get started writing a proposal

### PR DESCRIPTION
**Pull request by ahoppen**
Essentially, this is a paraphrased version of https://forums.swift.org/t/implementing-incremental-re-parsing-in-swiftparser-gsoc-2023/63291/2.

### CODE REVIEW

**Review by ktoso — APPROVED** [review]
This is good additional info -- thank you!

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Comment by ktoso** [comment]
@swift-ci please test

**Pull request merged**
