### PR TITLE
Add a new install page, update the download page, and move release yml files into one file.

### PR DESCRIPTION
**Pull request by shahmishal**
* New install page: 
127 0 0 1_4000_install_ (1)

* Removed all of the release dir in `_data/builds/swift-*-release`, and replaced it with one yml file `_data/builds/swift_releases.yml`
* Release info is defined in one place `_data/builds/swift_releases.yml`
* Updated the download page

TODO: Update the code sign info on download page

### CODE REVIEW

**Comment by gwynne** [comment]
Wow, this is great! Are you planning a corresponding PR in apple/swift-docker to update the use of the `latest-build.yml` files similarly?

**Comment by shahmishal** [comment]
> Wow, this is great! Are you planning a corresponding PR in [swift-docker](https://github.com/apple/swift-docker) to update the use of the `latest-build.yml` files similarly?

We are still going to use the latest-build.yml for now

**Comment by tomerd** [comment]
@shahmishal per feedback from the core team review, could you update "Apple Platforms" to "macOS" so we can get this merged? We are looking to open a PR against main and this is one missing piece

**Comment by shahmishal** [comment]
> @shahmishal per feedback from the core team review, could you update "Apple Platforms" to "macOS" so we can get this merged? We are looking to open a PR against main and this is one missing piece

Currently the download page says "Apple Platforms". 
https://www.swift.org/download/#using-downloads

Screenshot 2023-07-14 at 5 05 18 PM

**Comment by shahmishal** [comment]
After thinking more about "where" to install the toolchain compared what it's used for. Going to update the title for "Apple Platforms" to "macOS"

**Comment by tomerd** [comment]
@shahmishal is this ready to be merged?

**Review by alexandersandberg — APPROVED** [review]
There are some things left to improve here, e.g. renaming "Apple Platforms" to "macOS" as suggested above, and maybe making some styling changes based on discussions in the SWWG meetings.

With that said, I think it would be good to merge this PR as is as it's blocking us from opening the final content improvements PR against the main branch, and then make any final adjustments in that later PR instead.

**Comment by shahmishal** [comment]
I will clean it up today and get it merged.

**Comment by shahmishal** [comment]
Screenshot 2023-08-07 at 5 59 29 PM

**Comment by shahmishal** [comment]
Going to merge this we can handle additional feedback with new PR.

**Pull request merged**
