### PR TITLE
Release Swift 5.10.1 with new platforms Debian 12, Fedora 39, Ubuntu …

### PR DESCRIPTION
**Pull request by shahmishal**
…23.10, and Ubuntu 24.04

* Docker images will be available soon.

Screenshot 2024-06-05 at 10 26 56 PM

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test

**Review by 0xTim — APPROVED** [review]

**Comment by alexandersandberg** [comment]
I pushed two commits here:

- Fixed the Debian pages not working due to some typos (`debain`)
- Fixed the Debian and Fedora pages from mentioning the version name in the "Select {platform} version:" title

**Comment by alexandersandberg** [comment]
@swift-ci please test

**Review by alexandersandberg — APPROVED** [review]

**Comment by alexandersandberg** [comment]
@shahmishal please review my changes before merging though 🙂

**Comment by shahmishal** [comment]
@alexandersandberg thanks, not sure how missed that.

**Pull request merged**
