### PR TITLE
Add NIO on Windows GSoC proposal

### PR DESCRIPTION
**Pull request by finestructure**
cc @compnerd

### CODE REVIEW

**Review by FranzBusch — COMMENTED** [review]
I think this is a great project but we need to figure out the CI situation for Windows in the NIO repos first cc @compnerd @shahmishal

**Comment by ktoso** [comment]
That's a very good project, we'd need to ensure we have CI so the work isn't wasted and can actually be verified and accepted upstream.

Sounds like we need to chat about Windows CI again if we are to accept such GSoC idea // cc @shahmishal 

I'll see if I can set up a thread where we can talk about this

**Comment by ktoso** [comment]
I discussed the CI situation and with the NIO team, the team is not comfortable mentoring such project without CI so we can't really accept this idea.

We'd love to run it but it's not responsible to do so without CI, maybe next year.

**Comment by finestructure** [comment]
No worries and thanks for following up, Konrad!

**Pull request closed without merging**
