### PR TITLE
feat: add Contributor Experience Workgroup and Platforms Steering Group

### PR DESCRIPTION
**Pull request by louisunlimited**
### Motivation:
- #638 

### Modifications:

Added entries for `Contributor Experience Workgroup` and `Platforms Steering Group`, with description copied from each individual page while maintaining similar standards in wording as opposed to other group/workgroups.

### Result:

Contributor Experience Workgroup and Platforms Steering Group will be added

### CODE REVIEW

**Comment by shahmishal** [comment]
Thank you for working on this @louisunlimited. 

Suggestions: 

We should split the groups in two:
* **Steering Group**
   * Language
   * Platforms
* **Workgroup** 
   * C++ Interoperability
   * Contributor Experience
   * Documentation
   * Swift on Server
   * Website

**Comment by louisunlimited** [comment]
Hi @shahmishal, thank you for following up!

I added the "steering" text because I saw you have that for `Website Workgroup` so I thought it might be appropriate. I can also split those like you suggested if you'd like that.

**Comment by louisunlimited** [comment]
Screenshot 2024-04-18 at 10 15 57

**Comment by louisunlimited** [comment]
Please do let me know if there's more I can do, thanks!

**Comment by parispittman** [comment]
@louisunlimited thanks so much for this work!! I'd like to merge it as is but notes for others - 

Questions/comments for the other website maintainers:
- should we suggest to remove the "steering groups" and "workgroups" after each one now that they have proper headers that allude to what kind of group they are? 
- we still have a TBD on the definitions of the meta groups themselves 
We can do a follow up PR with that stuff if everyone is cool with it.

**Comment by kaishin** [comment]
@parispittman 

> should we suggest to remove the "steering groups" and "workgroups" after each one now that they have proper headers that allude to what kind of group they are?

That would be my vote as well to reduce information overload.

**Comment by louisunlimited** [comment]
Hi @kaishin , it's fixed how. Let me know if you need anything else.

**Comment by louisunlimited** [comment]
@parispittman @kaishin @shahmishal Hi all, sorry for the pin, but are there anything more I can do to help improve this?

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
Thanks @louisunlimited!

**Comment by parispittman** [comment]
@louisunlimited if you want to work on more related things like this, reach out to me on the forums in a DM and I can guide you. Haven't had the time to write issues about them.

**Pull request merged**
