### PR TITLE
list server and website workgroup emeritus

### PR DESCRIPTION
**Pull request by tomerd**
motivation: credit workgroup emeritus

changes:
* refactor website and server workgroup pages to use data files instead of hard coded names
* add list of workgroup emeritus to the website and server workgroup pages

### CODE REVIEW

**Review by shahmishal — APPROVED** [review]
Thanks LGTM!

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by tomerd** [comment]
@swift-ci test

**Comment by tomerd** [comment]
@swift-ci test

**Pull request merged**
