### PR TITLE
[gsoc] Add project idea: Tracing in HTTP client

### PR DESCRIPTION
**Pull request by ktoso**
Also add the required difficulty section and change the times to concrete hours, as GSoC requested, rather than "medium" etc.

### CODE REVIEW

**Comment by ktoso** [comment]
@swift-ci please =test

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
Hah, can't self approve :) 

Would you mind @alexandersandberg or @0xTim ?

**Review by alexandersandberg — APPROVED** [review]

**Comment by ktoso** [comment]
Thank you @alexandersandberg !

**Pull request merged**
