### PR TITLE
Adding `<meta name="theme-color" />` for docs

### PR DESCRIPTION
**Pull request by sanjaiyan-dev**
Adding  `<meta name="theme-color" />` for the docs. For more info https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color

I choosed `#f05138` as a theme-color hence it looks nice in dark mode and white mode too, and that colour in presents in `Swift` logo too.

_Sorry if I made any mistakes :(_

### CODE REVIEW

**Comment by alexandersandberg** [comment]
Thanks for contributing, @sanjaiyan-dev!

Adding a `theme-color` is a nice idea. While Swift's `#f05138` is a good choice, it's also a bold one to use with `theme-color`.

The screenshots below show what it looks like in Safari with compact tabs and the option to show colors in the tab bar.

Using theme-color on Swift.org in light mode
Using theme-color on Swift.org in dark mode

While I like the color, I think it needs to be discussed first before a PR is opened. I would suggest [opening an issue](https://github.com/apple/swift-org-website/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=) on the topic and closing this PR for now instead.

Do you agree?

---

_P.S. When contributing, make sure your personal linter is not changing code unrelated to the PR, like in https://github.com/apple/swift-org-website/pull/117/commits/611b3a707820f425025f1b4b3e373096719db92c._

**Comment by sanjaiyan-dev** [comment]
> Thanks for contributing, @sanjaiyan-dev!
> 
> Adding a `theme-color` is a nice idea. While Swift's `#f05138` is a good choice, it's also a bold one to use with `theme-color`.
> 
> The screenshots below show what it looks like in Safari with compact tabs and the option to show colors in the tab bar.
> 
> Using theme-color on Swift.org in light mode
> 
> Using theme-color on Swift.org in dark mode
> 
> While I like the color, I think it needs to be discussed first before a PR is opened. I would suggest [opening an issue](https://github.com/apple/swift-org-website/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=) on the topic and closing this PR for now instead.
> 
> Do you agree?
> 
> _P.S. When contributing, make sure your personal linter is not changing code unrelated to the PR, like in [611b3a7](https://github.com/apple/swift-org-website/commit/611b3a707820f425025f1b4b3e373096719db92c)._

Okay 🙌💪

**Comment by kaishin** [comment]
I will close this for now. This can be re-opened if the discussion reaches a conclusion on how we want to use theme color and which color to use.

**Comment by sanjaiyan-dev** [comment]
> I will close this for now. This can be re-opened if the discussion reaches a conclusion on how we want to use theme color and which color to use.

Hi, 
So do I need to open a new issue or it will be discussed under here ?

**Comment by sanjaiyan-dev** [comment]
> @sanjaiyan-dev Please open [a new issue](https://github.com/apple/swift-org-website/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=) 🙂

Ok 🤝

**Comment by sanjaiyan-dev** [comment]
> @sanjaiyan-dev Please open [a new issue](https://github.com/apple/swift-org-website/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=) 🙂

Done 🙌
https://github.com/apple/swift-org-website/issues/140

**Pull request closed without merging**
