### PR TITLE
Added macOS instructions for tools, first build, what's next

### PR DESCRIPTION
**Pull request by RobinBateman808**
### Motivation:

Add macOS instructions similar to Linux and Windows to help new users.

### Modifications:

Added instructions for tools, first build, and what's next.

### Result:

Help new users and beginners get started using step-by-step instructions and examples.

### CODE REVIEW

**Comment by RobinBateman808** [comment]
@shahmishal - per our review, here's the new macOS instruction page similar to what exists for Linux and Windows.

**Review by 0xTim — COMMENTED** [review]
Conflicts with #676

**Comment by RobinBateman808** [comment]
@0xTim - Noted and thank you.

**Comment by RobinBateman808** [comment]
Verified some editing/formatting changes published on <<https://www.swift.org/install/macos/package_installer/>>.

**Pull request closed without merging**
