### PR TITLE
Updated PGP/GPG text for installing Linux using Tarball

### PR DESCRIPTION
**Pull request by RobinBateman808**
### Motivation:

Update language for specificity.

### Modifications:

Cleaned up grammar and spelled out acronyms for PGP/GPG section. 

### Result:

Provide clarity and avoid confusion.

### CODE REVIEW

**Comment by RobinBateman808** [comment]
Hi @shahmishal - Here's the update for the PGP/GPG section.

**Review by 0xTim — COMMENTED** [review]
Should be adjusted to build on #676

**Comment by RobinBateman808** [comment]
@0xTim - Noted and thank you.

**Comment by RobinBateman808** [comment]
Verified minor editorial suggestions were implemented in the “Import and verify the PGP signature” section: <<https://www.swift.org/install/linux/tarball/>>.

**Pull request closed without merging**
