### PR TITLE
Optimizing script loading.

### PR DESCRIPTION
**Pull request by sanjaiyan-dev**
1) Preconnecting to required origins for [for improving page load speed 🚀 ](https://web.dev/uses-rel-preconnect)

2) Loading script using [defer attribute for preventing from DOM construction and rendering delays](https://web.dev/efficiently-load-third-party-javascript/#defer) or we can use [async attribute](https://web.dev/efficiently-load-third-party-javascript/#async) to execute the script as soon as fetching is completed.

_Extremely sorry if I made any mistakes :(_

### CODE REVIEW

**Comment by alexandersandberg** [comment]
Would it be possible to provide some numbers showing the impact of these changes?

**Comment by kaishin** [comment]
This a good initiative. We might want to hold off on merging this until we do some performance benchmarks as @alexandersandberg mentioned in his previous comment. 

@sanjaiyan-dev Any chance you can share the page speed report before and after? That would be very helpful.

**Comment by sanjaiyan-dev** [comment]
> This a good initiative. We might want to hold off on merging this until we do some performance benchmarks as @alexandersandberg mentioned in his previous comment. 
> 
> @sanjaiyan-dev Any chance you can share the page speed report before and after? That would be very helpful.

Hi,

Extremely sorry currently I don't have valid bench marks :( but I hope these changes are marked as good practise by the Google Chrome team :)

Sorry for the late response (@alexandersandberg & @kaishin )

**Comment by alexandersandberg** [comment]
I'm hesitant about these changes without any kind of benchmarks or proof that they will improve the website experience.

The first link in the PR description also recommends using `preload` over `preconnect`. Why is it better for us to use the latter?

**Comment by sanjaiyan-dev** [comment]
> The first link in the PR description also recommends using `preload` over `preconnect`. Why is it better for us to use the latter?

Sorry I have updated to preload  :)

**Comment by alexandersandberg** [comment]
@sanjaiyan-dev Thank you, but we still need to figure out the impact of this before considering a merge.

**Comment by kaishin** [comment]
I will close this PR due to inactivity. @sanjaiyan-dev Please feel free to re-open once you have the opportunity to address the feedback above.

**Pull request closed without merging**
