### PR TITLE
Fix examples in Windows installation options

### PR DESCRIPTION
**Pull request by stevapple**
Fix typos caused by copy-pasting in Windows installation guide, and make some essential improvements.

### Motivation:

Address https://forums.swift.org/t/swift-on-windows-guide/67534/8

### Modifications:

- Fix a typo caused by copy-pasting in WinGet and Scoop installation guide.
- Use `--id --exact` to enforce WinGet package lookup result.
- Bump recommended Visual Studio version from 2019 to 2022;
- Bump recommended Windows SDK version from 10.0.19041 to 10.0.22000.

### Result:

WinGet and Scoop guide should be usable again (and the WinGet part is more robust now).

### CODE REVIEW

**Comment by stevapple** [comment]
Anyone to review & merge, perhaps @shahmishal?

**Review by alexandersandberg — APPROVED** [review]
Looks fine to me, but maybe @compnerd can have a look as well.

**Review by compnerd — APPROVED** [review]

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@shahmishal @tomerd - can we get this merged?

**Comment by shahmishal** [comment]
@stevapple @compnerd can you help resolve the merge conflict?

**Comment by compnerd** [comment]
@shahmishal I don't see the resolve conflicts button (maybe because I'm not in the repository committers?).  I suspect that the python version is the conflict and the versioning that was merged is the correct version.

**Comment by stevapple** [comment]
> @stevapple @compnerd can you help resolve the merge conflict?

Done.

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@shahmishal @tomerd - seems ready to merge?

**Pull request merged**
