### PR TITLE
Add Swift 6.0 to evolutions list filter

### PR DESCRIPTION
**Pull request by alexandersandberg**
Add version 6.0 to the evolution list's implemented filter.

### Motivation:

As we have some proposals marked as implemented in Swift 6.0, we should add this version to the evolutions filter as well.

### Modifications:

- Adds `6.0` to the filter

### Result:

You can filter the evolutions list by "implemented in Swift 6.0" (currently 8 results).

CleanShot 2024-02-20 at 20 31 56

### CODE REVIEW

**Comment by alexandersandberg** [comment]
@swift-ci please test

**Comment by dempseyatgithub** [comment]
The language group is deciding (probably in a day or so) whether we want to move to using 'X.0' for major releases or stick with 'X'.

I've got PRs lined up to make the change in both places depending on which they decide.

In the interim, it looks very strange and inconsistent in the filter UI to have some major versions as '3', '4', '5' and then Swift 6 listed as '6.0'.

**Comment by dempseyatgithub** [comment]
@alexandersandberg I have a PR up for swift-evolution that implements the Language Steering Group decision. https://github.com/apple/swift-evolution/pull/2335

I also have put up https://github.com/apple/swift-org-website/pull/557 here which updates the past versions to match the new style and adds 6.0.

Sorry for the thrash on this.

**Comment by alexandersandberg** [comment]
IMO I still see value in merging this PR now instead of having to wait for the other one which is blocked.

**Review by dempseyatgithub — APPROVED** [review]
Yes, I was hoping the PR to swift-evolution would be merged quickly to avoid the inconsistency in the major number versioning in the filter interface.

But it's probably better to have the functionality to filter for the next release even with the version number inconsistency in the interim.

**Pull request merged**
