### PR TITLE
SSWG: Add Tibor to the members list

### PR DESCRIPTION
**Pull request by ktoso**
The previous PR was mentioning @tib but actually forgot to include him :)

https://github.com/apple/swift-org-website/pull/717

### CODE REVIEW

**Review by 0xTim — APPROVED** [review]

**Comment by 0xTim** [comment]
@swift-ci test

**Comment by ktoso** [comment]
Thanks Tim

**Comment by alexandersandberg** [comment]
Thanks, @ktoso! 🙏 Can't wait for live PR previews someday 😅

**Comment by ktoso** [comment]
Thank you for the previous Pr! :-)

**Pull request merged**
