### PR TITLE
Add SSWG Guides

### PR DESCRIPTION
**Pull request by 0xTim**
As per discussions at the last SWWG meeting, this PR ports across the [SSWG Guides](https://github.com/swift-server/guides) to be part of Swift.org.

I've added everything in what I think is a sensible way. Discoverability isn't great but at least they should be indexed by search engines and we can solve discoverability further down the line.

Images:

Screenshot 2022-07-26 at 21 44 01
Screenshot 2022-07-26 at 21 43 57
Screenshot 2022-07-26 at 21 41 24

### CODE REVIEW

**Comment by 0xTim** [comment]
@swift-ci test

**Review by alexandersandberg — COMMENTED** [review]
Great to finally have this hosted on Swift.org! 🙂 

There are 2 references to the old https://github.com/swift-server/guides/ in the [SSWG update blog post](https://www.swift.org/blog/sswg-update/). We should also update these to point to the new location.

I noticed some assets that are quite large and can be compressed further, e.g. using https://tinypng.com:
* `assets/images/server-guides/gcp-cloud-build.png`
* `assets/images/server-guides/gcp-cloud-run.png`
* `assets/images/server-guides/gcp-connect-repo.png`
* `assets/images/server-guides/swift-download-ubuntu-18-copy-link.png`

**Comment by 0xTim** [comment]
Updated!

**Comment by 0xTim** [comment]
@swift-ci test

**Review by alexandersandberg — APPROVED** [review]
Perfect! 🙂

**Review by TimTr — APPROVED** [review]

**Comment by tomerd** [comment]
lgtm. cc @tkremenek and @cthielen in case they have any feedback.

**Comment by tkremenek** [comment]
This looks good, but I wonder if we should also include a blog post?  I realize these resources have been available in some form for a while, but I think making a statement in a short blog post that talks about this content now being available on http://Swift.org gives us the opportunity to do some active communication about it, and have a swiftlang tweet.

**Comment by 0xTim** [comment]
I'm happy to do a blog post - guess it should be a separate PR

**Comment by 0xTim** [comment]
@swift-ci test

**Comment by 0xTim** [comment]
@swift-ci test

**Pull request merged**
