### PR TITLE
Improve code block design

### PR DESCRIPTION
**Pull request by alexandersandberg**
Improve code block design to use the same design as on the landing page.

### Motivation:

The current code blocks, with the blue, left border, look a bit off-brand in comparison to where the rest of the website is going in terms of design.

The feature code snippet on the landing page uses an improved style, and I think it would be nice to reuse this across the rest of the website as well.

_However, this change is of course opinionated, so feel free to disagree below!_

### Modifications:

- Update code block style
- Remove unused color variables

#### Light mode

Comparisons before and after for a code snippet found in the [On-device ML research with MLX and Swift](https://www.swift.org/blog/mlx-swift/) blog post.

|Before|After|
|---|---|
|||

#### Dark mode

|Before|After|
|---|---|
|||

## Mobile, with a scrolling code block

|Before|After|
|---|---|
|CleanShot 2024-02-24 at 10 32 44|CleanShot 2024-02-24 at 10 32 15|

### CODE REVIEW

**Comment by daveverwer** [comment]
This looks great. I prefer it to the blue bar 👍

**Comment by alexandersandberg** [comment]
@swift-ci please test

**Review by kaishin — APPROVED** [review]
A very welcome change as the line didn't seem to have an immediately clear aesthetic or utilitarian purpose.

**Review by dempseyatgithub — APPROVED** [review]
I think the change is a good one, it especially improves readability on mobile, where the bar blocks scrolled content.

One thing I noticed is that the border line is rounded, but the background color is not:

Screenshot 2024-02-25 at 2 59 37 AM

This seems to be the case with the code on the landing page as well.

I think the background should be rounded as well. However, that could be done as a separate PR.

**Comment by alexandersandberg** [comment]
> One thing I noticed is that the border line is rounded, but the background color is not:
> 
> Screenshot 2024-02-25 at 2 59 37 AM
> This seems to be the case with the code on the landing page as well.
> 
> I think the background should be rounded as well. However, that could be done as a separate PR.

Great catch, James! Apparently, this was caused by the `highlight` CSS being applied twice — both to the parent `div` and the `pre` tag. See this for more: https://talk.jekyllrb.com/t/different-syntax-highlighting-on-github-pages-and-locaklly/1084/6

I fixed it as suggested in that thread by only applying the syntax highlighting to the `<pre>` element by changing the CSS to target `pre.highlight` instead of just `.highlight` in [14a3948](https://github.com/apple/swift-org-website/pull/565/commits/14a39481c6f83a3d317abfa53b7e6cc9f735c066).

**Comment by alexandersandberg** [comment]
@swift-ci please test

**Review by federicobucchi — APPROVED** [review]

**Comment by alexandersandberg** [comment]
@swift-ci please test

**Pull request merged**
