### PR TITLE
Improve page authors styling

### PR DESCRIPTION
**Pull request by alexandersandberg**
Improved styling of page authors, to allow for adding more authors to pages and blog posts without taking up too much space and looking awkward.

### Motivation:

We've had more pages and blog posts with more than 1-2 authors lately, and it's taking up too much space. It also doesn't look great.

To remedy this, I thought we could only show the about info for authors if there are up to 2 authors for a page or blog post. If there are more than 2 authors, the authors are instead placed horizontally, and without the about info. The about info can instead be read by hovering over the author's avatar.

I went with 2 as the limit for showing the about info as it still looks good and doesn't take up too much space, and we only have 4 pages/blog posts at the moment with more than 2 authors at the moment.

### Modifications:

- Changed to a horizontal layout without about info when there are more than 2 authors for the page — the about info is instead displayed when hovering the avatar
- Refactored the styling to use modern CSS (flexbox)
- Fixed missing space between authors without about info
- Fixed an issue where an author's about info was applied to the next author if the next one was missing about info
- Also cleaned up the spacing a bit

### Result:

- If more than 2 authors, about info is only shown when hovering avatar, and authors are places horizontally
- No more incorrect about info for authors
- More consistent and nicer spacing

Preview: https://alexandersandberg-swift-org-website.netlify.app

#### 1-2 authors

|Before|After|
|---|---|
|Screenshot of post with 2 authors, before changes|Screenshot of post with 2 authors, after changes|

#### 3+ authors

|Before|After|
|---|---|
|Screenshot of post with 3 authors, before changes|Screenshot of post with 3 authors, after changes|

The list of authors also wraps nicely on mobile with these new changes, as seen here:

Screenshot of post with 3 authors, before changes, on mobile

### CODE REVIEW

**Comment by alexandersandberg** [comment]
@swift-ci please test

**Comment by dempseyatgithub** [comment]
I think with the changes there is now too much space between the author block and the beginning of the post text.

Previously there were about 23 points of space (which was broken if there was no 'about' info for an author, because the margin was part of the about, which is fixed in this PR!)

Overall, I think this is an excellent enhancement.

**Comment by alexandersandberg** [comment]
> I think with the changes there is now too much space between the author block and the beginning of the post text.
> 
> Previously there were about 23 points of space (which was broken if there was no 'about' info for an author, because the margin was part of the about, which is fixed in this PR!)

Appreciate the feedback! You're right—it's maybe a bit too much space now. What about this (reducing the space from `3em` to `2em`)?

CleanShot 2024-02-20 at 20 48 26
CleanShot 2024-02-20 at 20 48 33

**Comment by alexandersandberg** [comment]
Do we also want to reduce the space between the publishing date and the authors? I think looks better, especially when the post has 3+ authors:

|Before|After|
|---|---|
||CleanShot 2024-02-20 at 20 53 17|

|Before|After|
|---|---|
||CleanShot 2024-02-20 at 20 53 00|

**Comment by dempseyatgithub** [comment]
Playing around inspecting elements in my browser, 1.5em or 1.75em feel like a better spacing for the bottom of the authors to me.

I think it's because with a space bigger than that, it seems like the authors are more strongly associated visually with the title than the article that they authored.

I don't have a strong opinion either way regarding the date change.

And one additional thing I just noticed, for mobile with more than two authors, there seems to be too much space between rows of authors.

**Comment by alexandersandberg** [comment]
> Playing around inspecting elements in my browser, 1.5em or 1.75em feel like a better spacing for the bottom of the authors to me.

The problem with less space to me is that it visually blends the author bios with the article text when they are displayed, as can be seen here. Now it looks like it's a paragraph in the article.

CleanShot 2024-02-21 at 08 21 43

> I think it's because with a space bigger than that, it seems like the authors are more strongly associated visually with the title than the article that they authored.

As the list of authors is part of the metadata of the article, together with the publishing date, I don't see this as an issue, but maybe even something that _should_ visually belong to the header/meta than the rest of the article.

> And one additional thing I just noticed, for mobile with more than two authors, there seems to be too much space between rows of authors.

I reduced the gap a bit on mobile. I also reduced the gap between the author's image and their name, to visually increase the gap _between_ the authors, as they were blending together a bit.




CleanShot 2024-02-21 at 08 31 28
CleanShot 2024-02-21 at 08 31 10

**Comment by alexandersandberg** [comment]
@swift-ci please test

**Comment by dempseyatgithub** [comment]
> The problem with less space to me is that it visually blends the author bios with the article text when they are displayed, as can be seen here. Now it looks like it's a paragraph in the article.
> 
> CleanShot 2024-02-21 at 08 21 43
> 

In the screenshot above, the space between the authors and the first paragraph of text is actually *less space* than between the paragraphs in the article, so I'd agree that is not enough space in the above screen shot.

But when I take a screen shot with the bottom margin at 1.75em or even 1.5em there is more space between the authors and the first paragraph. This is at 1.5em bottom margin:

Screenshot 2024-02-23 at 10 03 28 AM

The new author spacing in the mobile layout looks great! 

But I think the size of the bottom margin at 2em looks especially large in the mobile layout.

I think it would probably make sense to have some other members of the group give feedback.

**Comment by kaishin** [comment]
@alexandersandberg Is it possible to share a preview or a screenshot of the latest spacing changes on mobile/desktop to make it easier for others to chime in?

**Comment by alexandersandberg** [comment]
> @alexandersandberg Is it possible to share a preview or a screenshot of the latest spacing changes on mobile/desktop to make it easier for others to chime in?

Good idea! Here's a deployed preview: https://alexandersandberg-swift-org-website.netlify.app

**Review by kaishin — APPROVED** [review]
While the spacing changes are subtle, the compact layout is a nice solution for multi-author posts.

I personally do not think the 2em bottom spacing is excessive, even on mobile. Even if it was, I don't think that's a merge blocker :+1:

**Comment by alexandersandberg** [comment]
Based on feedback from a workgroup meeting, I have made the following changes:

- Authors are now listed without bio at the beginning of the start of the blog post, no matter how many
- Authors are now also listed, _with bio_, at the end of the blog post, no matter how many

Two authors with bio at the start of the blog post, where bios are hidden

Two authors with bio at the end of the blog post, where bios are visible

Let me know what you think about this.

**Comment by daveverwer** [comment]
> Based on feedback from a workgroup meeting, I have made the following changes:
> 
> * Authors are now listed without bio at the beginning of the start of the blog post, no matter how many
> * Authors are now also listed, _with bio_, at the end of the blog post, no matter how many
> 

Visually, I think this is perfect. 👍👍👍 Thanks for hosting the preview, too. I checked out several posts and it looks good in every situation. 

The only thing I think isn't quite right is that I think the bios at the bottom are a little too hard to find if a click on the name still goes to their profile. I think my preference would be that a click on any name at the top would scroll you to the bottom, and then from there we can link to the profiles. However, if we want to make the profiles just one click away from the top, maybe we add a small sentence under the the author names at the top with some text like "Author biographies" which scrolls it down.

**Comment by alexandersandberg** [comment]
> The only thing I think isn't quite right is that I think the bios at the bottom are a little too hard to find if a click on the name still goes to their profile. I think my preference would be that a click on any name at the top would scroll you to the bottom, and then from there we can link to the profiles.

Yes, good points. If you hover over an author's avatar (only available on desktop though) you will see a tooltip with their bio. Not everyone will be aware of this though.

I'm just afraid that it's confusing that clicking the names at the top take you to the bottom and clicking them at the bottom takes you to GitHub, as they are visually the same other than their location on the page.

> However, if we want to make the profiles just one click away from the top, maybe we add a small sentence under the the author names at the top with some text like "Author biographies" which scrolls it down.

If possible, I think I would like to avoid adding more text or links here, as I like how simple it is now.

---

I wonder if it's really a problem to potentially miss these bios though. Most likely, the linked GitHub profiles will have a bio of their own of some kind.

**Comment by alexandersandberg** [comment]
@daveverwer @kaishin @dempseyatgithub Pinging you again for some feedback here as I'm not sure how we feel about the current state vs. making more changes.

**Comment by daveverwer** [comment]
> @daveverwer @kaishin @dempseyatgithub Pinging you again for some feedback here as I'm not sure how we feel about the current state vs. making more changes.

LGTM

**Comment by kaishin** [comment]
> @daveverwer @kaishin @dempseyatgithub Pinging you again for some feedback here as I'm not sure how we feel about the current state vs. making more changes.

The latest preview looks good. I thought about @daveverwer's suggestion even before reading his comment, but I ended up with the same conclusion as yours @alexandersandberg since they look identical and as such should behave identical.

**Comment by alexandersandberg** [comment]
Thanks! Will merge this then.

**Comment by alexandersandberg** [comment]
@swift-ci please test

**Pull request merged**
