### PR TITLE
Update URL of Spanish translation site

### PR DESCRIPTION
**Pull request by trsplms**
### Motivation:

Keep the Spanish translation updated with the correct URL.

### Modifications:

Added the production URL to the website where the Spanish translation of Swift documentation is hosted.

### Result:

The documentation's Spanish translation project is updated with the correct URL.

### CODE REVIEW

**Review by alexandersandberg — APPROVED** [review]
👍

And thanks for your work with the Spanish translation! 🙂

**Comment by alexandersandberg** [comment]
@swift-ci please test

**Comment by shahmishal** [comment]
@algoritmau we noticed `https://swiftbook.es` stopped working.

**Comment by algoritmau** [comment]
Hi, @shahmishal. Sorry, yes, I had to take some time off the digital world for personal reasons. I'm now back on getting this project up to speed to have the TSPL fully translated as soon as possible.

**Comment by shahmishal** [comment]
Welcome back! Thanks for looking into it.

**Pull request merged**
