### PR TITLE
Upgrade to Ruby 3.x and pin the Ruby version for a more consistent local development environment

### LINKED ISSUE #6: Missing webrick?
Installed ruby via rbenv.
```
rbenv versions
  system
* 3.0.2 (set by /Users/lex/.rbenv/version)
```
Then `bundle install` without errors.

It failed to run `LC_ALL=en_us.UTF-8 bundle exec jekyll serve`:
```servlet.rb:3:in require': cannot load such file -- webrick (LoadError)```

<details>
<summary>Error output</summary>
bash
Configuration file: /Users/lex/g/swift-org-website/_config.yml
            Source: /Users/lex/g/swift-org-website
       Destination: /Users/lex/g/swift-org-website/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 1.477 seconds.
 Auto-regeneration: enabled for '/Users/lex/g/swift-org-website'
                    ------------------------------------------------
      Jekyll 4.2.1   Please append `--trace` to the `serve` command
                     for any additional information or backtrace.
                    ------------------------------------------------
/Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/lib/jekyll/commands/serve/servlet.rb:3:in `require': cannot load such file -- webrick (LoadError)
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/lib/jekyll/commands/serve/servlet.rb:3:in `<top (required)>'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/lib/jekyll/commands/serve.rb:179:in `require_relative'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/lib/jekyll/commands/serve.rb:179:in `setup'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/lib/jekyll/commands/serve.rb:100:in `process'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `each'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/exe/jekyll:15:in `<top (required)>'
	from /Users/lex/.rbenv/versions/3.0.2/bin/jekyll:23:in `load'
	from /Users/lex/.rbenv/versions/3.0.2/bin/jekyll:23:in `<top (required)>'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.8/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.8/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.8/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.8/lib/bundler/cli.rb:484:in `exec'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.8/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.8/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.8/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.8/lib/bundler/cli.rb:31:in `dispatch'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.8/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.8/lib/bundler/cli.rb:25:in `start'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.8/exe/bundle:48:in `block in <top (required)>'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.8/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.8/exe/bundle:36:in `<top (required)>'
	from /Users/lex/.rbenv/versions/3.0.2/bin/bundle:23:in `load'
	from /Users/lex/.rbenv/versions/3.0.2/bin/bundle:23:in `<main>'
</details>

Once I add webrick with bundle everything works great.
`bundle add webrick`

### PR DESCRIPTION
**Pull request by daveverwer**
Fixes #6 

This PR does a few different things. They are all related, though, so I think they belong in a single PR.

These changes initially came out of getting the site up and running on my local machine. As the project did not have a `.ruby-version` file, it ran with my globally defined version of ruby, which is a 3.x version installed via `rbenv`. That exposed the problem I mention in point 2 below, and the other changes follow on from there.

The improvements are:

1. Pinned a Ruby version with a `.ruby-version` file so that people with `rbenv` or `rvm`will automatically have the correct version of Ruby selected when building the site without using Docker.
2. Added an explicit import of the `webrick` gem. Jekyll on Ruby 2.x did not require this, but running it on 3.x does. There’s no new dependency here, just a change from implicit to explicit import. There is [more information here](https://github.com/jekyll/jekyll/issues/8523) if needed.
3. Older versions of Bundler output a warning when running with Ruby 3.x so I also upgraded Bundler to 2.3.13. There is [more information here](https://github.com/rubygems/rubygems/issues/5234) if needed.
4. Applied the same changes to the `Dockerfile` so that everything stays in sync.
5. I also changed the `Gemfile` to allow patch version upgrades to Jekyll itself via running `bundle update`.
6. I ran a `bundle update` to update to the latest patch version of Jekyll.

Happy to discuss any of this or split any of these changes into separate PRs if that would be preferred. If upgrading to Ruby 3.x is not desirable then just adding a `.ruby-version` file specifying 2.7.x would also allow people with `rbenv` or `rvm`to run the site locally. However, I would recommend we upgrade to 3.x (which is why I did it!)

I have tested all these changes with both Ruby 2.x and Ruby 3.x so if people do have a different installation of Ruby 2.x installed, everything will still work. I also tested it with the system Ruby installation, where it does crash. 😬 However, I then checked whether it also crashed using system Ruby *without* these changes and I get the same result, so it’s not something I have introduced here.

Happy to discuss any of this or split any of these changes into separate PRs if that would be preferred. If upgrading to Ruby 3.x is not desirable then just adding a `.ruby-version` file specifying 2.7.x would also allow people with `rbenv` or `rvm`to run the site locally. However, I would recommend we upgrade to 3.x (which is why I did it!)

### CODE REVIEW

**Comment by daveverwer** [comment]
I just noticed that this had been logged as a bug in #6, too.

**Comment by tomerd** [comment]
@swift-ci test

**Review by tomerd — APPROVED** [review]

**Review by 0xTim — APPROVED** [review]
🙌 for the Ruby expert! I agree upgrading everything to the latest and greatest makes sense

**Comment by tomerd** [comment]
@swift-ci test

**Comment by tomerd** [comment]
@shahmishal wdyt?

**Comment by shahmishal** [comment]
@daveverwer Thank you for updating the Ruby version! I will merge this later today (need to make sure deployment goes smoothly)

**Review by shahmishal — APPROVED** [review]

**Comment by shahmishal** [comment]
Changes are now live! sorry for reverts @daveverwer.

**Pull request merged**
