### PR TITLE
[sswg] Fix date format

### PR DESCRIPTION
**Pull request by 97mik**

### CODE REVIEW

**Review by 0xTim — APPROVED** [review]
As much as I dislike this - thanks!

The SWWG should probably discuss what standard we want to stick to because this date format is confusing to everyone outside the US

**Comment by 0xTim** [comment]
@swift-ci test

**Comment by alexandersandberg** [comment]
+1 for a more international date format. 😁

**Comment by Kyle-Ye** [comment]
> The international standard recommends writing the date as year, then month, then the day: YYYY-MM-DD.
> Source: https://en.wikipedia.org/wiki/Date_format_by_country

Should we use align them to be something like 2022-09-29?

**Comment by 0xTim** [comment]
> Should we align them all to be something like 2022-09-29?

Yeah we need to discuss this and then audit the site for all the other instances of the ~wrong~ American formatting

**Pull request merged**
