### PR TITLE
SSWG projects and members update

### PR DESCRIPTION
**Pull request by finestructure**
- Adds MongoKitten as an incubated project
- Adds myself as a new member

### CODE REVIEW

**Review by ktoso — APPROVED** [review]
LGTM -- wasn't there some other file we need to edit -- the package collection? 🤔 

We can find that via chat @finestructure

**Comment by finestructure** [comment]
Yes, I've got that here: https://github.com/swift-server/sswg-collection/pull/10

Or did you mean within the swift website repo?

**Comment by alexandersandberg** [comment]
I believe adding it to **_data/server-workgroup/projects.yml** should be enough for this repo. 🙂

**Review by alexandersandberg — APPROVED** [review]

**Comment by alexandersandberg** [comment]
@swift-ci please test

**Comment by finestructure** [comment]
Acceptance posted: https://forums.swift.org/t/sswg-0027-mongokitten/69249/6

**Comment by finestructure** [comment]
@swift-ci please test

**Comment by alexandersandberg** [comment]
@swift-ci please test

**Comment by alexandersandberg** [comment]
@swift-ci test

**Comment by alexandersandberg** [comment]
Ready to merge?

**Comment by finestructure** [comment]
Fine by me!

**Comment by finestructure** [comment]
Thanks Alex!

**Review by KidiIT — COMMENTED** [review]
Reviewed and tested all equipment for safety precautions ❤️🫶@finestructure

**Comment by KidiIT** [comment]
Reviewed and approved all items for inspection and final approval for all items🫶❤️

**Pull request merged**
