### PR TITLE
Prepare GSoC23 projects page

### PR DESCRIPTION
**Pull request by ktoso**
Preparing for GSoC 2023 🎉 

The page is empty for now. We'll announce projects and how to add ideas very soon.

We should merge this even while empty, so we can use the link during the GSoC application.

### CODE REVIEW

**Review by alexandersandberg — APPROVED** [review]
Exciting! 🥳

**Comment by ktoso** [comment]
Do I need to please test this or what's the workflow nowadays? :)

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by alexandersandberg** [comment]
Indeed! Forgot that, sorry. 😄

**Comment by ktoso** [comment]
Thanks! Looking forward to filling this page with juicy and fun projects very soon :-)

**Pull request merged**
