### PR TITLE
Update instructions for new translation projects

### PR DESCRIPTION
**Pull request by patternina**
### Motivation:

Swift.org recommends users inform the organization about new translation projects by reaching out to the Compiler Developer forums.

> If you know of a quality translation project underway, please let us know on the [Compiler Development](https://forums.swift.org/c/development/compiler) forums, and we’ll provide a link to that project on this page.

However, since the website is now open source, users should be advised to submit such information via a Pull Request.

### Modifications:

Modified the paragraph to advise users to inform about new translation projects via submission of a Pull Request on this repository.

### Result:

Users can simply submit a Pull Request to inform the Swift Organization about new translation projects so they can add a link.

### CODE REVIEW

**Review by alexandersandberg — APPROVED** [review]
Thanks! I think this change is fine. Will wait for someone else to chime in as well.

**Comment by alexandersandberg** [comment]
@swift-ci please test

**Comment by dempseyatgithub** [comment]
I think this change ends up making it more difficult to submit the information.

Instead of posting a message to a forum, the person submitting the info needs to set up a fork of this repo, edit the page directly, and submit a PR.

I wonder if we should change the instructions to send a direct message on the forums to the website workgroup OR submit a pull request.

That would keep a simpler option available, but make it so the workgroup is contacted directly while also suggesting the PR.

**Comment by alexandersandberg** [comment]
>...change the instructions to send a direct message on the forums to the website workgroup OR submit a pull request.

Yes, I think that's even better. 👍

**Comment by dempseyatgithub** [comment]
The name and link to use in the text about contacting the website workgroup is [@swift-website-workgroup](https://forums.swift.org/new-message?groupname=swift-website-workgroup).

**Review by dempseyatgithub — DISMISSED** [review]
Marking this as requesting changes so it doesn’t get accidentally merged. Please see earlier comments for requested change.

Also, @trsplms, thank you for suggesting this change.

I believe these instructions are from before the site was open source and before the website workgroup was formed, so I think updating the instructions is a good change.

**Comment by kaishin** [comment]
Should opening an issue be considered an option as well? It might be the easiest of the three options.

**Comment by dempseyatgithub** [comment]
> Should opening an issue be considered an option as well? It might be the easiest of the three options.

Yes, opening an issue is probably a better option than sending a message to the workgroup on the Swift forums.

I don’t think we want too many options, but “open an issue or submit a PR” would probably be the best two.

**Comment by gfpoliva** [comment]
Hey people, hope you're all good! :)

Is there a reason not to center the translations in this repo instead of having multiple side project from different people accross the globe?

**Comment by 0xTim** [comment]
@gfpoliva I think long term that might be easiest (and one we've transitioned to in Vapor) - however we need to have the infrastructure in place in order to deploy the translations etc so it will be a long way off

**Review by alexandersandberg — APPROVED** [review]

**Comment by alexandersandberg** [comment]
@swift-ci please test

**Pull request merged**
