### PR TITLE
Robins install linux overview

### PR DESCRIPTION
**Pull request by RobinBateman808**
### Motivation:

Fix typo.

### Modifications:

Changed word from "our" to "your". 

### Result:

Mitigate confusion.

### CODE REVIEW

**Comment by RobinBateman808** [comment]
@shahmishal  - fixed typo and removed an extra line space between overview and next section.

**Review by 0xTim — APPROVED** [review]
This LGTM but the change should probably be applied to the branch #676 uses

**Comment by 0xTim** [comment]
@swift-ci test

**Comment by RobinBateman808** [comment]
@0xTim - Noted and thanks for your input.

**Comment by RobinBateman808** [comment]
Verified no editing and formatting suggestions implemented/required on page <<https://www.swift.org/install/linux/#platforms>> due to new wireframe redesign.

**Pull request closed without merging**
