### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by tomerd**
add chris to blog area code owners

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
We should update the CODEOWNERS file at root of the repository https://github.com/apple/swift-org-website/blob/main/CODEOWNERS

```
/_post/* @cthielen @hborla @TimTr @tkremenek @tomerd
```

**Comment by tomerd** [comment]
@shahmishal updated

**Review by shahmishal — APPROVED** [review]
Thanks

**Comment by tomerd** [comment]
@swift-ci test

**Pull request merged**
