### PR TITLE
[Download] Add UBI9 aarch64 for Swift 5.8

### PR DESCRIPTION
**Pull request by shahmishal**
Screenshot 2023-03-13 at 11 45 49 AM

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test

**Review by FranzBusch — APPROVED** [review]

**Review by MaxDesiatov — APPROVED** [review]
Thanks!

**Comment by tomerd** [comment]
I think we should say "Red Hat Universal Base Image", that is the full name of the platform  https://www.redhat.com/en/blog/introducing-red-hat-universal-base-image

**Comment by shahmishal** [comment]
@swift-ci test

**Pull request merged**
