### PR TITLE
Overhaul Debug Perf Issues and Analysis documentation

### PR DESCRIPTION
**Pull request by RobinBateman808**
### Motivation:

Edited Debug Performance Issues and Analysis documentation to increase helpfulness.

### Modifications:

Overhauled page content by adding definitions and clarity to existing content, editing for grammar and complete sentences, reducing wordiness, providing additional instructions for less-skilled users, and formatting for scannability.

### Result:

Improve usefulness and increase user adoption.

### CODE REVIEW

**Comment by RobinBateman808** [comment]
@OxTim, Here's another rewrite of the guides as requested by Franz Busch. Feel free to provide as much feedback as needed for further clarity and/or improvements. Thank you! :-)

**Comment by 0xTim** [comment]
@RobinBateman808 I'm assuming this is to replace https://github.com/apple/swift-org-website/blob/main/documentation/server/guides/performance.md ? We should make sure we port the changes to that file (even if it's just an overwrite) otherwise this new page won't be linked anywhere

**Comment by RobinBateman808** [comment]
@0xTim - yes, it replaces that file. Noted, and will TAL to correct. Thanks!

**Comment by RobinBateman808** [comment]
@0xTim - Closing this PR. See [PR #616](https://github.com/apple/swift-org-website/pull/616) for documentation changes.

**Pull request closed without merging**
