### PR TITLE
add new Server guide for deploying to AWS Lambda

### PR DESCRIPTION
**Pull request by dave-moser**
### Motivation:

show developers how to deploy Swift Server on AWS Lambda

### Modifications:

Added a new markdown file with the contents of the guide]

### Result:

new page under server guides

### CODE REVIEW

**Comment by 0xTim** [comment]
@swift-ci test

**Review by 0xTim — APPROVED** [review]
Looks great! One nit but otherwise LGTM

Is the code on a GH repo anywhere for people to refer to?

**Comment by dave-moser** [comment]
Nothing in a GH repo at this point. Everything is in the doc. We could look at publishing a sample though. Maybe in the examples folder of the Lambda Runtime repo?

**Comment by 0xTim** [comment]
@swift-ci test

**Comment by 0xTim** [comment]
@dave-moser I think it would be good to put it _somewhere_ but in a separate repo (matches the rest of the guides). We could always put it in https://github.com/swift-server-community/

**Comment by tomerd** [comment]
nice 👍 thanks for putting together

**Pull request merged**
