### PR TITLE
SSWG: Cassandra client is accepted

### PR DESCRIPTION
**Pull request by ktoso**
The proposal review of https://forums.swift.org/t/sswg-0021-swift-cassandra-client/62658 concluded and accepted the library

### CODE REVIEW

**Comment by ktoso** [comment]
@swift-ci please test

**Review by tomerd — APPROVED** [review]

**Comment by alexandersandberg** [comment]
Do we want these projects in a `/data` `.yml` file? Might make it easier, and prevent formatting mistakes. If so, I can try to add one.

**Comment by tomerd** [comment]
looks like something got lost in translation here when moving from GH to the website. this should be based on a YAML and we probably need to update the one to reflect the current hard coded list

**Comment by alexandersandberg** [comment]
I opened a PR here: https://github.com/apple/swift-org-website/pull/232

**Pull request merged**
