### PR TITLE
Add Documentation Workgroup documents

### PR DESCRIPTION
**Pull request by franklinsch**
Adds a blog post and a charter document for the new Documentation Workgroup!

### CODE REVIEW

**Review by TimTr — APPROVED** [review]
Looks good

**Comment by tkremenek** [comment]
These changes have been reviewed with the core team, and are considered approved by the core team.

**Comment by cthielen** [comment]
@swift-ci test

**Comment by cthielen** [comment]
@swift-ci test

**Comment by tkremenek** [comment]
@swift-ci test

**Pull request merged**
