### PR TITLE
Removed Active signing keys content

### PR DESCRIPTION
**Pull request by RobinBateman808**
### Motivation:

Move Active signing keys content to add to a new subsidiary page focused on verifying builds.

### Modifications:

Removed Active signing and Expired keys content.

### Result:
Simplify and refocus the Linux Installation Options page on the installation process only.

### CODE REVIEW

**Comment by RobinBateman808** [comment]
@shahmishal - removed content as suggested to simplify and focus on the install only.

**Review by 0xTim — COMMENTED** [review]
Probably conflicts with #676

**Comment by RobinBateman808** [comment]
@0xTim - Noted and thank you.

**Comment by RobinBateman808** [comment]
Verified <<https://www.swift.org/install/windows/traditional/#active-signing-keys>> section was removed in new redesign.

**Pull request closed without merging**
