### PR TITLE
Tweak SwiftUI tutorial

### PR DESCRIPTION
**Pull request by 0xTim**
Adds screenshots the SwiftUI Tutorial.

I've also updated the code blocks so we get syntax highlighting. I've left the 1st person text as we don't have a style guide (nor do I think we should have one) and it reads well

### CODE REVIEW

**Review by kaishin — COMMENTED** [review]
Excellent additions, especially the screenshots.

I've optimized the images for ~50% reduction in size, which is significant enough to warrant replacing the ones in the PR. I attached the zip of the optimized images.

My 2 cents regarding the gif: videos tend to be smaller, better quality, and provide more control over playback, including the ability to pause them for preference or accessibility reasons. If you still have the source video around it might be beneficial to include it in the PR to keep the option to switch open before merging to main.

[optimized-images.zip](https://github.com/apple/swift-org-website/files/10754611/optimized-images.zip)

**Comment by 0xTim** [comment]
IIRC we had issues embedding the video in the markdown for another PR so switched to a Gif? Can anyone remember?

**Review by tomerd — APPROVED** [review]

**Comment by 0xTim** [comment]
@kaishin here you go, thanks!


https://user-images.githubusercontent.com/9938337/219863989-c26c9901-9a7b-4dc8-9fc7-9e038ddac75b.mov

**Comment by kaishin** [comment]
@0xTim I'll get around this later today. Do you want me to replace the images as well and push to this branch?

**Comment by 0xTim** [comment]
@kaishin if you could that would be awesome! 🙌

**Review by kaishin — APPROVED** [review]
@0xTim Feel free to merge!

**Pull request merged**
